# Dependencies
markdown:         kramdown
highlighter: rouge
kramdown:
    input: GFM
    hard_wrap: false
# Permalinks
permalink:        pretty

# Setup
title:            Dots &Holes
tagline:          'A blog'
description:      'Okay well keep it brief'
url:              
baseurl:          ''
author:
  name:           'Rimjhim Surana'
  url:            

paginate:         5

# Custom vars
version:          2.1.0
