# Dependencies
markdown:         kramdown
highlighter: rouge
kramdown:
    input: GFM
    hard_wrap: false
# Permalinks
permalink:        pretty

# Setup
title:            Dots &Holes
tagline:          'A blog'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              
baseurl:          ''
author:
  name:           'Rimjhim Surana'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

prose:
  rooturl: ''
  siteurl: http://www.burnedsap.github.io/
  media: assets
  metadata:
    _posts:
    - name: title
      field:
        label: title
        element: text
        value: title
    - name: layout
      field:
        label: layout
        element: text
        value: post
    - name: date
      field:
        label: date
        element: text
        value: CURRENT_DATETIME
    - name: author
      field:
        label: author
        element: text
        value: Salil
    - name: categories
      field:
        label: categories
        element: text
        placeholder: Enter categories separated by commas
    - name: tags
      field:
        label: tags
        element: text
        placeholder: Enter tags separated by commas
