# Dependencies
markdown:         kramdown
highlighter: rouge
kramdown:
    input: GFM
    hard_wrap: false
# Permalinks
permalink:        pretty

# Setup
title:            Dots &Holes
tagline:          'A blog'
description:      'Cant seem to get rid of it'
url:              
baseurl:          'https://dotsandholes.github.io/'
author:
  name:           'Rimjhim Surana'
  url:            

paginate:         5

prose:
  rooturl: ''
  siteurl: http://www.dotsandholes.github.io/
  media: assets
  metadata:
    _posts:
    - name: title
      field:
        label: title
        element: text
        value: title
    - name: layout
      field:
        label: layout
        element: text
        value: post
    - name: date
      field:
        label: date
        element: text
        value: CURRENT_DATETIME
    - name: author
      field:
        label: author
        element: text
        value: Rimjhim
    - name: categories
      field:
        label: categories
        element: text
        placeholder: Enter categories separated by commas
    - name: tags
      field:
        label: tags
        element: text
        placeholder: Enter tags separated by commas
